### PR TITLE
Simplify home screen design

### PR DESCRIPTION
**Pull request by devinjameson**
Why: we would like to have a simpler home screen design that requires less development overhead and looks great on all devices.

Screen Shot 2020-08-27 at 5 41 29 PM

### CODE REVIEW

**Comment by devinjameson** [comment]
@amandabeiner Want to merge this into the clean up PR whenever you're ready?

**Comment by amandabeiner** [comment]
@devinjameson Maybe we should get CR on the other PR, merge it, and rebase & merge this one? Just concerned about making the other PR too big to review

**Comment by devinjameson** [comment]
> @devinjameson Maybe we should get CR on the other PR, merge it, and rebase & merge this one? Just concerned about making the other PR too big to review

@amandabeiner Sounds good to me!

**Comment by amandabeiner** [comment]
LGTM! 🎉

**Pull request merged**
