### PR TITLE
Redirect the user to settings screen instead of app info

### PR DESCRIPTION
**Pull request by juancruzgs**
#### Description:

When the user taps on "Open settings" we are currently showing the "App Info" screen. This screen doesn't allow the user to enable Location or Bluetooth.

This PR redirects the user to the "Settings" screen where the user can enable the required services.
I'm redirecting the user to the general settings screen because some devices won't find specific setting detail screens.

#### Linked issues:

https://pathcheck.atlassian.net/browse/GAEN-236

#### Screenshots:

Before:
device-2020-09-08-145529

After:
device-2020-09-08-145501

### CODE REVIEW

**Comment by juancruzgs** [comment]
@mattThousand I'm using some of your code in `mb-open-settings-natively`, we can merge them in a single PR if your branch is ready

**Comment by mattThousand** [comment]
> @mattThousand I'm using some of your code in `mb-open-settings-natively`, we can merge them in a single PR if your branch is ready

great, thanks @juancruzgs - pushed a commit for the iOS piece

**Review by johnschoeman — APPROVED** [review]
LGTM, only thought is that the `utils` native module probably doesnt need to be in the same file as the gaen native module, but this be picked up in a refactor commit.

**Comment by juancruzgs** [comment]
@mattThousand Unit tests are failing for iOS
```
[!] Invalid `Podfile` file: syntax error, unexpected '\n', expecting =>.

 #  from /Users/runner/work/gaen-mobile/gaen-mobile/ios/Podfile:53
 #  -------------------------------------------
 #    use_native_modules!
 >  end
 #  
 #  -------------------------------------------
```

**Pull request merged**
