### PR TITLE
GAEN-685 Return error when there are no keys to submit

### PR DESCRIPTION
**Pull request by juancruzgs**
#### Why:

We user was seeing a Success message when he doesn't have keys to submit

#### This commit:

Returns a Failure instead to let the user know we didn't have anything to send to the backend

### CODE REVIEW

**Comment by juancruzgs** [comment]
@artgibson Could you help me test this branch?

**Review by johnschoeman — APPROVED** [review]
LGTM

**Comment by juancruzgs** [comment]
I haven't tested it because I'll need a VPN and a phone number
If someone could test it quickly please let me know if it works okay

**Review by artgibson — COMMENTED** [review]
@juancruzgs  I tested a build with this, but was unable to get a "correct" error message that matched No Keys on Device. Only received "Something Went Wrong, Try Again".

My test included:

1. Deleting app and removing random ids from device
2. Re-installing app fresh and then submitting a phone number.


@johnschoeman do we know if this error from android will get bubbled properly to react native layer to show these messages: https://github.com/Path-Check/gaen-mobile/blob/develop/src/locales/en.json#L530

**Comment by juancruzgs** [comment]
We are sending the error code "999" to the JS layer
It may be worth debugging this method in JS to check what's happening

```
export const submitDiagnosisKeys = async (
  verificationCode: string,
  date: Posix,
): Promise<SubmitKeysResponse> => {
  try {
    await escrowVerificationKeySubmissionModule.submitDiagnosisKeys(
      verificationCode,
      date,
    )
    return { kind: "success" }
  } catch (e) {
    Logger.error(`failed to submit verification code: `, { ...e })
    switch (e.code) {
      case "999":
        return { kind: "failure", error: "NoKeysOnDevice" }
      default:
        return { kind: "failure", error: "Unknown" }
    }
  }
}
```

**Comment by johnschoeman** [comment]
@artgibson , @juancruzgs , we are handling this in the view layer: https://github.com/Path-Check/gaen-mobile/blob/develop/src/EscrowVerification/VerificationCodeForm.tsx#L101.

I would agree with Juan in that the issue is probably with `submitDiagnosisKeys`, likely something is off with the error shape and its defaulting to 'Unknown' rather than 'NoKeysOnDevice'

Im happy to put a commit onto this branch if you'd like Juan, but I think this pr could be shipped as is and i can take a look at fixing the JS side in a future commit.

**Review by artgibson — APPROVED** [review]
lgtm. we can review react-native layer for error message. cc @johnschoeman

**Comment by juancruzgs** [comment]
Sounds good to me

**Pull request merged**
