### PR TITLE
Update pull lokalise script for android

### PR DESCRIPTION
**Pull request by aledustet**
Why:
----
The android file structure for the localization files was of the form:
`android/app/src/bt/res/values-{LANG_ISO}/strings.xml`

This is incorrect, the files should be stored in the structure
`android/app/src/bt/res/values/strings-{LANG_ISO}.xml`

This Commit:
----
- Remove incorrect file structure for translations on android project
- Update arguments for pulling files for the android project and unzipping them
- Execute pull script for android new file structure

### CODE REVIEW

**Comment by aledustet** [comment]
Apparently the previous file structure `was` correct. please do not review until we have the response

**Comment by alpita-masurkar** [comment]
No.. the previous file structure was of the form android/app/src/bt/res/values-ar/android/app/src/bt/res/values-ar/string.xml,
it should be like what you said in the description:android/app/src/bt/res/values/strings-{LANG_ISO}.xml


as you can probably see here. Did you see this too
image

**Comment by juancruzgs** [comment]
@aledustet The format should be `android/app/src/bt/res/values-{LANG_ISO}/strings.xml`

**Comment by aledustet** [comment]
Closing in favor of #105

**Pull request closed without merging**
